export const GET_DETAIL_MOVIE = 'GET_DETAIL_MOVIE'

export const LOADING_DETAIL = 'LOADING_DETAIL'
export const DETAIL_MOVIE_SUCCESS = 'DETAIL_MOVIE_SUCCESS'
export const DETAIL_MOVIE_FAIL = 'DETAIL_MOVIE_FAIL'